apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dot
  region: us-east-1
managedNodeGroups:
  - name: primary
    instanceType: t2.small
    minSize: 3
    maxSize: 6
    spot: true
